const ref = (name: string) => ({ $ref: `#/$defs/${name}` })
const arrayOf = (items: Record<string, unknown>, defaultValue?: unknown) => ({
  type: "array",
  ...(defaultValue === undefined ? {} : { default: defaultValue }),
  items,
})
const itemSchema = (properties: Record<string, unknown>, required: string[]) => ({
  allOf: [ref("itemBase")],
  properties,
  required,
  unevaluatedProperties: false,
})
const sectionSchema = (item: Record<string, unknown>) => ({
  allOf: [ref("baseSection")],
  properties: { items: arrayOf(item) },
  required: ["items"],
  unevaluatedProperties: false,
})

export const resumeSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  type: "object",
  properties: {
    picture: ref("picture"),
    basics: ref("basics"),
    summary: ref("summary"),
    sections: ref("sections"),
    customSections: ref("customSections"),
    metadata: ref("metadata"),
  },
  required: ["picture", "basics", "summary", "sections", "customSections", "metadata"],
  additionalProperties: {},
  $defs: {
    website: {
      type: "object",
      properties: { url: { type: "string" }, label: { type: "string" } },
      required: ["url", "label"],
      additionalProperties: false,
    },
    itemWebsite: {
      type: "object",
      default: { url: "", label: "", inlineLink: false },
      properties: {
        url: { type: "string" },
        label: { type: "string" },
        inlineLink: { type: "boolean", default: false },
      },
      required: ["url", "label", "inlineLink"],
      additionalProperties: false,
    },
    icon: { type: "string" },
    iconColor: { type: "string", default: "" },
    picture: {
      type: "object",
      properties: {
        hidden: { type: "boolean" },
        url: { type: "string" },
        size: { type: "number", minimum: 32, maximum: 512 },
        rotation: { type: "number", minimum: 0, maximum: 360 },
        aspectRatio: { type: "number", minimum: 0.5, maximum: 2.5 },
        borderRadius: { type: "number", minimum: 0, maximum: 100 },
        borderColor: { type: "string" },
        borderWidth: { type: "number", minimum: 0 },
        shadowColor: { type: "string" },
        shadowWidth: { type: "number", minimum: 0 },
      },
      required: ["hidden", "url", "size", "rotation", "aspectRatio", "borderRadius", "borderColor", "borderWidth", "shadowColor", "shadowWidth"],
      additionalProperties: false,
    },
    customField: {
      type: "object",
      properties: {
        id: { type: "string" },
        icon: ref("icon"),
        text: { type: "string" },
        link: { type: "string", default: "" },
      },
      required: ["id", "icon", "text", "link"],
      additionalProperties: false,
    },
    basics: {
      type: "object",
      properties: {
        name: { type: "string" },
        headline: { type: "string" },
        email: { type: "string" },
        phone: { type: "string" },
        location: { type: "string" },
        website: ref("website"),
        customFields: arrayOf(ref("customField")),
      },
      required: ["name", "headline", "email", "phone", "location", "website", "customFields"],
      additionalProperties: false,
    },
    summary: {
      type: "object",
      properties: {
        title: { type: "string" },
        icon: { type: "string", default: "" },
        columns: { type: "integer", minimum: 1, maximum: 6, default: 1 },
        enabled: { type: "boolean", default: true },
        hidden: { type: "boolean" },
        keepTogether: { type: "boolean", default: false },
        startOnNewPage: { type: "boolean", default: false },
        content: { type: "string" },
      },
      required: ["title", "icon", "columns", "enabled", "hidden", "keepTogether", "startOnNewPage", "content"],
      additionalProperties: false,
    },
    itemBase: {
      type: "object",
      properties: { id: { type: "string" }, hidden: { type: "boolean" } },
      required: ["id", "hidden"],
    },
    role: {
      type: "object",
      properties: {
        id: { type: "string" },
        position: { type: "string" },
        period: { type: "string" },
        description: { type: "string" },
      },
      required: ["id", "position", "period", "description"],
      additionalProperties: false,
    },
    summaryItem: itemSchema(
      { id: { type: "string" }, hidden: { type: "boolean" }, content: { type: "string" } },
      ["id", "hidden", "content"],
    ),
    coverLetterItem: itemSchema(
      { recipient: { type: "string" }, content: { type: "string" } },
      ["recipient", "content"],
    ),
    awardItem: itemSchema(
      { title: { type: "string", minLength: 1 }, awarder: { type: "string" }, date: { type: "string" }, website: ref("itemWebsite"), description: { type: "string" } },
      ["title", "awarder", "date", "website", "description"],
    ),
    certificationItem: itemSchema(
      { title: { type: "string", minLength: 1 }, issuer: { type: "string" }, date: { type: "string" }, website: ref("itemWebsite"), description: { type: "string" } },
      ["title", "issuer", "date", "website", "description"],
    ),
    educationItem: itemSchema(
      { school: { type: "string", minLength: 1 }, degree: { type: "string" }, area: { type: "string" }, grade: { type: "string" }, location: { type: "string" }, period: { type: "string" }, website: ref("itemWebsite"), description: { type: "string" } },
      ["school", "degree", "area", "grade", "location", "period", "website", "description"],
    ),
    experienceItem: itemSchema(
      { company: { type: "string", minLength: 1 }, position: { type: "string" }, location: { type: "string" }, period: { type: "string" }, website: ref("itemWebsite"), description: { type: "string" }, roles: arrayOf(ref("role"), []) },
      ["company", "position", "location", "period", "website", "description", "roles"],
    ),
    interestItem: itemSchema(
      { icon: ref("icon"), iconColor: ref("iconColor"), name: { type: "string", minLength: 1 }, keywords: arrayOf({ type: "string" }, []) },
      ["icon", "iconColor", "name", "keywords"],
    ),
    languageItem: itemSchema(
      { language: { type: "string", minLength: 1 }, fluency: { type: "string" }, level: { type: "number", minimum: 0, maximum: 5, default: 0 } },
      ["language", "fluency", "level"],
    ),
    profileItem: itemSchema(
      { icon: ref("icon"), iconColor: ref("iconColor"), network: { type: "string", minLength: 1 }, username: { type: "string" }, website: ref("itemWebsite") },
      ["icon", "iconColor", "network", "username", "website"],
    ),
    projectItem: itemSchema(
      { name: { type: "string", minLength: 1 }, period: { type: "string" }, website: ref("itemWebsite"), description: { type: "string" } },
      ["name", "period", "website", "description"],
    ),
    publicationItem: itemSchema(
      { title: { type: "string", minLength: 1 }, publisher: { type: "string" }, date: { type: "string" }, website: ref("itemWebsite"), description: { type: "string" } },
      ["title", "publisher", "date", "website", "description"],
    ),
    referenceItem: itemSchema(
      { name: { type: "string", minLength: 1 }, position: { type: "string" }, website: ref("itemWebsite"), phone: { type: "string" }, description: { type: "string" } },
      ["name", "position", "website", "phone", "description"],
    ),
    skillItem: itemSchema(
      { icon: ref("icon"), iconColor: ref("iconColor"), name: { type: "string", minLength: 1 }, proficiency: { type: "string" }, level: { type: "number", minimum: 0, maximum: 5, default: 0 }, keywords: arrayOf({ type: "string" }, []) },
      ["icon", "iconColor", "name", "proficiency", "level", "keywords"],
    ),
    volunteerItem: itemSchema(
      { organization: { type: "string", minLength: 1 }, location: { type: "string" }, period: { type: "string" }, website: ref("itemWebsite"), description: { type: "string" } },
      ["organization", "location", "period", "website", "description"],
    ),
    baseSection: {
      type: "object",
      properties: {
        title: { type: "string" },
        icon: { type: "string", default: "" },
        columns: { type: "integer", minimum: 1, maximum: 6, default: 1 },
        enabled: { type: "boolean", default: true },
        hidden: { type: "boolean" },
        keepTogether: { type: "boolean", default: false },
        startOnNewPage: { type: "boolean", default: false },
      },
      required: ["title", "icon", "columns", "enabled", "hidden", "keepTogether", "startOnNewPage"],
    },
    profilesSection: sectionSchema(ref("profileItem")),
    experienceSection: sectionSchema(ref("experienceItem")),
    educationSection: sectionSchema(ref("educationItem")),
    projectsSection: sectionSchema(ref("projectItem")),
    skillsSection: sectionSchema(ref("skillItem")),
    languagesSection: sectionSchema(ref("languageItem")),
    interestsSection: sectionSchema(ref("interestItem")),
    awardsSection: sectionSchema(ref("awardItem")),
    certificationsSection: sectionSchema(ref("certificationItem")),
    publicationsSection: sectionSchema(ref("publicationItem")),
    volunteerSection: sectionSchema(ref("volunteerItem")),
    referencesSection: sectionSchema(ref("referenceItem")),
    sectionType: {
      type: "string",
      enum: ["summary", "profiles", "experience", "education", "projects", "skills", "languages", "interests", "awards", "certifications", "publications", "volunteer", "references", "cover-letter"],
    },
    customSection: {
      allOf: [ref("baseSection")],
      properties: {
        id: { type: "string" },
        type: ref("sectionType"),
        items: arrayOf({
          anyOf: [
            ref("coverLetterItem"),
            ref("summaryItem"),
            ref("profileItem"),
            ref("experienceItem"),
            ref("educationItem"),
            ref("projectItem"),
            ref("skillItem"),
            ref("languageItem"),
            ref("interestItem"),
            ref("awardItem"),
            ref("certificationItem"),
            ref("publicationItem"),
            ref("volunteerItem"),
            ref("referenceItem"),
          ],
        }),
      },
      required: ["id", "type", "items"],
      unevaluatedProperties: false,
    },
    sections: {
      type: "object",
      properties: {
        profiles: ref("profilesSection"),
        experience: ref("experienceSection"),
        education: ref("educationSection"),
        projects: ref("projectsSection"),
        skills: ref("skillsSection"),
        languages: ref("languagesSection"),
        interests: ref("interestsSection"),
        awards: ref("awardsSection"),
        certifications: ref("certificationsSection"),
        publications: ref("publicationsSection"),
        volunteer: ref("volunteerSection"),
        references: ref("referencesSection"),
      },
      required: ["profiles", "experience", "education", "projects", "skills", "languages", "interests", "awards", "certifications", "publications", "volunteer", "references"],
      additionalProperties: false,
    },
    customSections: arrayOf(ref("customSection")),
    fontWeight: { type: "string", enum: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] },
    typographyItem: {
      type: "object",
      properties: {
        fontFamily: { type: "string" },
        fontWeights: arrayOf(ref("fontWeight"), ["400"]),
        fontSize: { type: "number", minimum: 6, maximum: 24, default: 11 },
        lineHeight: { type: "number", minimum: 0.5, maximum: 4, default: 1.5 },
      },
      required: ["fontFamily", "fontWeights", "fontSize", "lineHeight"],
      additionalProperties: false,
    },
    pageLayout: {
      type: "object",
      properties: { fullWidth: { type: "boolean" }, main: arrayOf({ type: "string" }), sidebar: arrayOf({ type: "string" }) },
      required: ["fullWidth", "main", "sidebar"],
      additionalProperties: false,
    },
    layout: {
      type: "object",
      properties: { sidebarWidth: { type: "number", minimum: 10, maximum: 50, default: 35 }, pages: arrayOf(ref("pageLayout")) },
      required: ["sidebarWidth", "pages"],
      additionalProperties: false,
    },
    page: {
      type: "object",
      properties: {
        gapX: { type: "number", minimum: 0 },
        gapY: { type: "number", minimum: 0 },
        marginX: { type: "number", minimum: 0 },
        marginY: { type: "number", minimum: 0 },
        format: { type: "string", enum: ["a4", "letter", "free-form"], default: "a4" },
        locale: { type: "string", default: "en-US" },
        hideLinkUnderline: { type: "boolean", default: false },
        hideIcons: { type: "boolean", default: false },
        hideSectionIcons: { type: "boolean", default: true },
      },
      required: ["gapX", "gapY", "marginX", "marginY", "format", "locale", "hideLinkUnderline", "hideIcons", "hideSectionIcons"],
      additionalProperties: false,
    },
    level: {
      type: "object",
      properties: { icon: ref("icon"), type: { type: "string", enum: ["hidden", "circle", "square", "rectangle", "rectangle-full", "progress-bar", "icon"] } },
      required: ["icon", "type"],
      additionalProperties: false,
    },
    colors: {
      type: "object",
      properties: { primary: { type: "string" }, text: { type: "string" }, background: { type: "string" } },
      required: ["primary", "text", "background"],
      additionalProperties: false,
    },
    design: { type: "object", properties: { level: ref("level"), colors: ref("colors") }, required: ["level", "colors"], additionalProperties: false },
    typography: { type: "object", properties: { body: ref("typographyItem"), heading: ref("typographyItem") }, required: ["body", "heading"], additionalProperties: false },
    template: { type: "string", enum: ["azurill", "bronzor", "chikorita", "ditgar", "ditto", "gengar", "glalie", "kakuna", "lapras", "leafish", "meowth", "onyx", "pikachu", "rhyhorn", "scizor"] },
    metadata: {
      type: "object",
      properties: {
        template: { ...ref("template"), default: "onyx" },
        layout: ref("layout"),
        page: ref("page"),
        design: ref("design"),
        typography: ref("typography"),
        notes: { type: "string" },
        styleRules: { default: [] },
      },
      required: ["template", "layout", "page", "design", "typography", "notes", "styleRules"],
      additionalProperties: false,
    },
  },
} as const
